services:
  Nano\EntityCsvImporterBundle\Service\CsvEntityImporter\:
    resource: '../src/Service/ConfigSorter.php'
    public: true
  Nano\EntityCsvImporterBundle\Service\ConfigSorter\:
    resource: '../src/Service/ConfigSorter.php'
  Nano\EntityCsvImporterBundle\Service\CsvImporterFactory\:
    resource: '../src/Service/CsvImporterFactory.php'
  Nano\EntityCsvImporterBundle\Service\ValueProcessor\:
    resource: '../src/Service/ValueProcessor.php'