services:
  Nano\EntityCsvImporterBundle\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Import/'
      - '../src/Types/'
      - '../src/NanoEntityCsvImporterBundle.php'

    Nano\EntityCsvImporterBundle\Service\CsvEntityImporter:
      public: true